#!/bin/bash
#
# Generate the configuration file for po4a.
#

if [ $0 != './l10n/scripts/gen-config.sh' ]; then
  echo 'Run this script from the reopsitory base directory!' >&2
  exit 1
fi

CONFIG_FILE='l10n/po4a.conf'

echo '# WARNING: Automatically generated by gen-config.sh, DO NOT MODIFY MANUALLY!'  > $CONFIG_FILE
echo ''                                                                             >> $CONFIG_FILE
echo '[po_directory] l10n'                                                          >> $CONFIG_FILE
echo '[po4a_alias:tldrpage] text opt:"-o markdown -o neverwrap -M UTF-8 -L UTF-8"'  >> $CONFIG_FILE
echo ''                                                                             >> $CONFIG_FILE

for fname in pages/**/*.md; do
  page=`cut -d'/' -f2- <<< $fname`
  echo '[type:tldrpage] '"$fname"' $lang:pages.$lang/'"$page"'' >> $CONFIG_FILE
done
